### ISSUE TITLE
Transaction ID is missing

### ISSUE THREAD

**Issue by 9zenith** [omise/omise-prestashop#24]
Hello,

Is it possible to have a transaction id (maybe charge_id), automatically updated to the order payment table?

![2017-06-18_14-55-24](https://user-images.githubusercontent.com/6650404/27259153-5904454e-5436-11e7-9fdf-9fa7f2cb303b.jpg)

As you can see from the above image, the success transaction was added to the invoice, but it lacks transaction_id to help admin match the transaction in the shop with Omise dashboard.

Thanks

**Comment by nimid** [comment]
@9zenith Hello,

Thank you very much for helping submit the issue.

This issue has been solved with the [release v1.2](https://github.com/omise/omise-prestashop/releases/tag/v1.2).

For more detail information about this issue, it can be found in the pull request #26.

**Comment by 9zenith** [comment]
Thank you so much for the solution!
It's working fine now.
