### ISSUE TITLE
Failed Charge Issue

### ISSUE THREAD

**Issue by 9zenith** [omise/omise-prestashop#25]
Hello,

When I tried using those failed cards to charge on the shop (as shown on https://www.omise.co/api-testing).

Cards with issue:
- Fail Pre-auth aka Invalid Security Code
- Fail 3DS Card Enrollment
- Fail 3DS Card Validation

The 3 above cards were causing issues, since the payment is failed, but Order Status is still in "ProcessingInProgress" state, I think the Order Status should be updated to "Canceled" like other cases as well.

**Comment by nimid** [comment]
@9zenith Hello,

Thank you very much for helping submit the issue.

This issue has been solved with the [release v1.2](https://github.com/omise/omise-prestashop/releases/tag/v1.2).

For more detail information about this issue, it can be found in the pull request #27.

**Comment by 9zenith** [comment]
Thank you so much for the solution!
It's working fine now.
