### ISSUE TITLE
Can't find the version 1.7.1.2

### ISSUE THREAD

**Issue by Tomohug** [omise/omise-prestashop#28]
I need to use omise for prestashop 1.7.1.2 what should i do

**Comment by nimid** [comment]
Hello @Tomohug ,

Thank you very much for your help in show the demand to use the PrestaShop version, 1.7. Your demand and suggestion are very value for us.

Support for version 1.7.x.x is on our plan.

Now, we can not say the exact time to finish but once the development is complete, we will release and announce for you to use.

**Comment by hassadee** [comment]
@nimid I also need Omise for Prestashop 1.7 as well. :-P

**Comment by nimid** [comment]
@hassadee Ok.

**Comment by boonyawat** [comment]
Is your module compatible with PS 1.6.1.14 and php7? Thank you.

**Comment by nimid** [comment]
@boonyawat Yes. The module, Omise PrestaShop, is compatible with PrestaShop 1.6.1.14 and PHP 7.

**Comment by boonyawat** [comment]
@nimid  I have technical question about Prestashop module. Should I ask here or is there support email for me to ask?

I installed the module, it works fine. But I would like to change some process flow.

Thanks

**Comment by guzzilar** [comment]
@boonyawat you can ask here as well :D

**Comment by boonyawat** [comment]
@guzzilar Great!

In the checkout page, a list of available payment options is displayed for a customer to choose. (E.g. bank transfer, paypal, omise.). For each one after clicking it, it will goes to another page. For instance, for wire transfer, it will go to other page that will display amount with other information before a customer can click confirm. For paypal, it will go to paypal interface for login, and amount and click confirm.

But with Omise, a customer will put in credit card information on the checkout page. And click on submit payment for 'actual' payment. There is no place for like 'confirming' message.

The way it is setup now may be user friendly but I think it is better to direct to another page for credit card information.

The question is.... can I put this credit card information block in another page? not on checkout page.

Thank you



![screen shot 2017-08-17 at 4 11 08 pm](https://user-images.githubusercontent.com/30367129/29407623-2baa92ac-836f-11e7-89a1-c38d74afea68.png)

**Comment by sutouch08** [comment]
@nimid | also need Omise for Prestashop 1.7.2

**Comment by tanapon395** [comment]
I also need Omise for Prestashop 1.7 as well. :-P

**Comment by nimid** [comment]
@Tomohug @hassadee @sutouch08 and @tanapon395 

Hi, Please check the new version of Omise PrestaShop, [v1.4](https://github.com/omise/omise-prestashop). This version has been modified to work with PrestaShop 1.7.

For more detail information about modification in this version, it can be found in the pull request #47.

Please provide your valuable feedback to us. So we can improve and meet your needs.
