### ISSUE TITLE
Alipay integration and automatic currency conversion

### ISSUE THREAD

**Issue by tihonnsk** [omise/omise-prestashop#55]
Alipay integration is in demand.
Also, automatic currency conversion may be convenient, when a customer uses his own currency but payment is run in Omise native currency.

**Comment by nimid** [comment]
Hello @tihonnsk ,

Thank you for your help to suggest your demands.

We will bring your requirements into our team discussion for the roadmap.

**Comment by jonrandy** [comment]
@tihonnsk Can I ask what version of PrestaShop you are using?

**Comment by tihonnsk** [comment]
PS 1.6.1.17

**Comment by jonrandy** [comment]
We have just released a new version (v1.7) of the plugin, that includes Alipay support. Compatibility with Prestshop 1.6 has also been restored. You may download the new release [here](https://github.com/omise/omise-prestashop/releases/download/v1.7/omise-prestashop-v1.7.zip)

**Comment by tihonnsk** [comment]
It's great!

What about automatic currency conversion?

I tried to install v1.7 module on local server on PS1.6 and got 2 issues:

1. When trying to make card payment I got "omiseCheckout is not defined" error in console. Though script is loaded on the page.

2. When trying to make Alipay payment I got error 500.

**Comment by jonrandy** [comment]
Can I ask what API version you are using?

**Comment by tihonnsk** [comment]
2015-11-17. If I need a new version is it a big problem to change?

**Comment by jonrandy** [comment]
That version should be fine. At what point do you get the 500 error?

**Comment by tihonnsk** [comment]
When I press Alipay button. And when I try to pay with a card and enter card details nothing happens and "omiseCheckout is not defined" error in console.

**Comment by jonrandy** [comment]
Hmmm... this is odd, I cannot reproduce either problem. Can you let me know:

1) Are you testing `live` or `test` mode?
2) What browser you are testing with?
3) The exact version of Prestashop you are using?
4) Exactly how you have the plugin set up? (maybe sending a screen grab of the settings is easiest here)
5) The version of PHP you are using

**Comment by tihonnsk** [comment]
I tried to install at the real shop and the problems are the same. Send me your contact and I will send you admin login to BO and FTP to check.

**Comment by tihonnsk** [comment]
Test mode, Mozilla, PS 1.6.1.17, PHP 5.6.35

**Comment by jonrandy** [comment]
jonathan@omise.co

**Comment by jonrandy** [comment]
Is everything ok now?

**Comment by tihonnsk** [comment]
It seems to me that everything works well. Thank you!
