### ISSUE TITLE
PrestaShop 1.7.3.0 Omise 1.4 is not in available in Payment Methods

### ISSUE THREAD

**Issue by Bogomazof** [omise/omise-prestashop#56]
Omise 1.4 was successfully installed on PrestaShop 1.7.3.0 and appears in Modules
But it is not available in Payment Methods

**Comment by jonrandy** [comment]
I'm checking with PrestaShop about this, but it seems that 3rd party payment modules like ours will only appear in the 'Modules > Installed Modules' admin page. Please let me know if you have success finding it there

**Comment by jonrandy** [comment]
Did this solve your issue?

**Comment by DarthCoder117** [comment]
Reporting that I am experiencing the same issue. Can see the Omise module in Installed Modules and in the restrictions section for payment methods, but can't tell if it's really enabled or not.

PrestaShop: v1.7.5.0
Omise: v1.7.3

**Comment by ghost** [comment]
Common guys. In installed modules locate Omise and click configure to set all required.
