### ISSUE TITLE
Cannot make payment  [URGENT]

### ISSUE THREAD

**Issue by boonyawat** [omise/omise-prestashop#57]
Hello

- Today customers cannot make payment on my website. This is just happening today. Yesterday I successfully received credit card payment from customer.

- I have tried the Test mode and it is working fine.

- I attached error screen shot with this email.

Thank you
Ont

PS 1.6.1.17
Omise 1.2
![screen shot 2018-03-30 at 4 46 30 pm](https://user-images.githubusercontent.com/30367129/38133996-9533a0a6-343b-11e8-8b5e-fd56d178e320.png)

**Comment by jonrandy** [comment]
Hi there. Are you still experiencing this problem?

**Comment by boonyawat** [comment]
No. Not anymore. I don’t know what causes the problem. I didn’t change anything. The problem just gone.

Thanks for checking

Boon
