### ISSUE TITLE
JS inside payment methods does not work in "One Page" checkout on PS1.6

### ISSUE THREAD

**Issue by jonrandy** [omise/omise-prestashop#64]
When PrestaShop 1.6 is set to "One Page" checkout mode, most (all?) Omise payment methods are broken. This is because javascript within inline script blocks in the payment methods templates does not run when these blocks are added to the page via AJAX

**Comment by jonrandy** [comment]
A solution for this problem has been identified. It will appear in an upcoming release

**Comment by jonrandy** [comment]
This issue is now fixed in release [v1.7.1](https://github.com/omise/omise-prestashop/releases/download/v1.7.1/omise-prestashop-v1.7.1.zip)

**Comment by tihonnsk** [comment]
To upgrade can I just save new files over old ones?

**Comment by jonrandy** [comment]
That would probably work, but I would advise going through the normal installation procedure. You may need to uninstall and remove the old version first. If you use the normal installation procedure, you will need to reconfigure the plugin afterwards
