### ISSUE TITLE
Last Version Error. Prestashop 1.6.1.15

### ISSUE THREAD

**Issue by kongkiat** [omise/omise-prestashop#67]
Template 'module:omise/views/templates/front/webhooks.tpl' not found
at line 66 in file classes/controller/ModuleFrontController.php

61.      * @throws PrestaShopException
62.      */
63.     public function setTemplate($template)
64.     {
65.         if (!$path = $this->getTemplatePath($template)) {
66.             throw new PrestaShopException("Template '$template' not found");
67.         }
68. 
69.         $this->template = $path;
70.     }
71. 
ModuleFrontControllerCore->setTemplate - [line 55 - modules/omise/controllers/front/webhooks.php] - [1 Arguments]
OmiseWebhooksModuleFrontController->postProcess - [line 178 - classes/controller/Controller.php]
ControllerCore->run - [line 367 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

**Comment by jonrandy** [comment]
This is now fixed. New bugfix release for this and a few other bugs coming very soon

**Comment by jonrandy** [comment]
Bugfix release released! https://github.com/omise/omise-prestashop/releases/tag/v1.7.2
