### ISSUE TITLE
Need auto convert from customer's currency to THB

### ISSUE THREAD

**Issue by tihonnsk** [omise/omise-prestashop#70]
Prestashop allows you to have multiple currencies for the convenience of the customer, but Omise allows to pay in Thai baht only. The function of automatic conversion of customer's currency into Thai baht at the payment process is very necessary. Otherwise, payment does not pass. Previous versions of the module at least reported that currency is not allowed for this method of payment. Now Omise is simply not displayed.

**Comment by aashishgurung** [comment]
We’re going to close this since there hasn’t been any activity on this issue for a while. If you think it's still relevant, please feel free to reopen it and we’ll take another look.
