### ISSUE TITLE
Got an error Order not found when success payment create (Prestashop 1.7.6.4)

### ISSUE THREAD

**Issue by noobookbig** [omise/omise-prestashop#85]
I have got an error "Order not found" when success payment create , test on sandbox mode **on Internet Banking payment** Prestashop** version 1.7.6.4  , Check on the sandbox payment was create successfully

**Comment by jonrandy** [comment]
Hi there. At what point do you see this error? Can you provide a screenshot?

**Comment by noobookbig** [comment]
Hi , To reproduce the error.
1. Select payment by internet banking (any bank)
2. Make an order
3. After Click on Success case

![Capture](https://user-images.githubusercontent.com/12130745/76929425-b4b24380-6916-11ea-97b3-83996ae07a52.JPG)
![Capture2](https://user-images.githubusercontent.com/12130745/76929430-b67c0700-6916-11ea-8fb3-e1f8c17154af.JPG)
![Capture3](https://user-images.githubusercontent.com/12130745/76929432-b7149d80-6916-11ea-8937-3d797c8b0c9b.JPG)

An Error occur.

Admin Log show as below
![log](https://user-images.githubusercontent.com/12130745/76934161-327b4c80-6921-11ea-8986-18fa0e2b990e.JPG)

**Comment by jonrandy** [comment]
Could you please try again? I think this may be related to an issue on the Omise servers

**Comment by noobookbig** [comment]
Oh it's working now Thank you.

**Comment by jonrandy** [comment]
Sorry for the disruption. Let us know if you have any more issues

**Comment by noobookbig** [comment]
Dear Jonrandy

We have got the issue again, I don't know which is caused by the omise server or not. Could you please check it for us. 

This has happened in production and sandbox also
1. When user order the product and pay by internet banking or credit card
2. Page loading 
3. Page show timeout Error
4. User get the email status order is processing
5. Omise dashboard show status pending
![omi](https://user-images.githubusercontent.com/12130745/78419515-bc8d1a00-7670-11ea-8a7b-82d8fe612540.JPG)
![log](https://user-images.githubusercontent.com/12130745/78419527-dfb7c980-7670-11ea-958f-9a2ecf45fa1b.JPG)

**Comment by noobookbig** [comment]
Ok, I found it, It causes by PHP mail function are not working properly.
