### ISSUE TITLE
User cancel payment on KTB Live mode , Prestashop said order is confirmed to user

### ISSUE THREAD

**Issue by noobookbig** [omise/omise-prestashop#88]
When user cancel payment on KTB Live mode , Prestashop said order is confirmed to the user with reference id.
Module Version 1.7.6
Step to reproduce on live mode
1. Select pay via internet banking
2. Select KTB
3. Click on cancel payment on KTB Page
4. KTB Will redirect to shop
5. Shop show order is confirm.
6. Admin Area on the order show Order is processing

Prestashop version 1.7.6.4

**Comment by jonrandy** [comment]
Unfortunately this is a known issue that has been present since we launched the internet banking method. We hope to fix this in the future

**Comment by noobookbig** [comment]
Oh Thank you
