### ISSUE TITLE
Update from 1.7.6 to 1.7.8 Module payment not working anymore

### ISSUE THREAD

**Issue by noobookbig** [omise/omise-prestashop#89]
On Prestashop 1.7.6.4 with module 1.7.6 are working when we have updated to 1.7.8 module is not working correctly. when user selects any payment and click on pay the page will be redirect to itself which happened on sandbox and live mode.

**Comment by jonrandy** [comment]
I have not been able to reproduce this. Does this happen on all browsers? Are their any errors?

**Comment by noobookbig** [comment]
I have got only info from the admin log

Informative only (1) | Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart | Cart | 67 | 0 | 2020-04-07 11:29

Yes, it has happened on all browser. 
It does not show any error on the page when debug mode is enabled so it reloads the page itself. Try to clear cache does not solve it also.

**Comment by jonrandy** [comment]
Did you clear both the browser cache and all of PrestaShop's caches?

**Comment by noobookbig** [comment]
Yes I have clear all cache.

**Comment by jonrandy** [comment]
Do you have any other PrestaShop plugins active?

**Comment by noobookbig** [comment]
I have only the theme plugins.

![screencapture-zugarmellow-admin500683iz7-index-php-improve-modules-manage-2020-04-07-12_12_19](https://user-images.githubusercontent.com/12130745/78632388-14be5900-78c9-11ea-9f3e-8445de7b2908.png)

**Comment by jonrandy** [comment]
Is it possible I can look at the site? If so, you can send the details to jonathan@omise.co

**Comment by noobookbig** [comment]
Ok Information sent to your email

**Comment by noobookbig** [comment]
Dear Jon, I have found the issue.


![ssl](https://user-images.githubusercontent.com/12130745/78764642-0a778a00-79b1-11ea-90ab-6fc480a1c803.JPG)
The issue caused by there are some insecure endpoint which is using HTTP request however on Prestashop setting I have to enable Force SSL on all page, I have workaround to get this working by not use strict mode on Cloudflare it will replace HTTP request by https and using Cloudflare certificate.

**Comment by jonrandy** [comment]
OK. I've made a small change to remove the need for the workaround. Thanks again for helping with this
